version: '3.1'
services:
  task-manager:
    image: 709005612718.dkr.ecr.ap-south-1.amazonaws.com/task-manager:1.0
    ports:
      - 5000:5000
    networks:
      - task-manager-aws
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      task-manager-aws:
        ipv4_address: 172.18.0.2
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - task-manager-aws
    depends_on:
      - mongodb

networks:
  task-manager-aws:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
    

