spring:
  application:
    name: Hotel-Service
  datasource:
    url: jdbc:postgresql://172.17.0.3:5432/hotel_service
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
      enabled: true  
      sampling:
        probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans